version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_HOST=${OPENAI_API_HOST}
      - OPENAI_API_TYPE=${OPENAI_API_TYPE}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_DEPLOYMENT_ID=${AZURE_DEPLOYMENT_ID}
      - NEXT_PUBLIC_DEFAULT_TEMPERATURE=0.1
